### ISSUE TITLE
renater infrastructure

### ISSUE THREAD

**Issue by eiro** [sympa-community/dotorg#1]
* vm requested, on its way
* dns entries to ask when we'll be ready

**Comment by eiro** [comment]
such a bad idea ...

**Comment by racke** [comment]
This is a public repository, so it would be helpful to let the community know why that is a bad idea ..

**Comment by racke** [comment]
It has been closed because specific infrastructure is not relevant to this repository, which was set up to plan for a new Sympa website.

**Comment by eiro** [comment]
the plan during the hackathon was to ask renater to provide an hosting solution. I handled it and they even made a better proposition that the one i asked for (they just need time) .... then someone decided it's not enough ... closing this ticket is a bad idea but i can provide not even a start of a valid explanation .... actually it sadden me.
